openapi: 3.0.3
info:
  title: WasaText
  description: | 
    This is the yaml documentation for the WasaText Api
  version: 1.0.0
paths:
  /session:
    post:
      tags:
        - login
      summary: Logs in the user
      description: >
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    example: "1"
  /conversations:
    get:
      tags:
        - conversations
      summary: Get all the users's conversations 
      description: >
        Get all the user conversations in a list.
      operationId: getMyConversations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
  /conversations/start-conversation:
    post:
      tags:
        - conversations
      summary: Start a new private conversation (1:1)
      description: >
        Starts a new conversation with another user and returns the id of the conversation.
      operationId: createPrivateConversation
      security:
        - bearerAuth: []
      requestBody:
        description: Conversation details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                username:
                  type: string
                  example: "hanniPham"
      responses:
        '200':
          description: Existing conversation found
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    example: "1"
        '201':
          description: New conversation created
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    example: "1"
        '400':
          description: Invalid request
        '404':
          description: User not found
  /conversations/get-details/{conversation_id}:
    get:
      tags:
        - conversations
      summary: Get a specific conversation
      description: > 
        Once given an ID, it returns a specific conversation
      operationId: getConversation
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/conversation_id'
      responses:
        '200':
          description: Details of the conversation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found
  /conversations/delete/{conversation_id}:
    delete:
      tags:
        - conversations
      summary: Delete a conversation
      operationId: deleteConversation
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/conversation_id'
      responses:
        '204':
          description: Conversation deleted successfully
        '404':
          description: Conversation not found
        '403':
          description: Forbidden
  /conversations/messages/{conversation_id}:
    get:
      tags:
        - messages
      summary: Get all messages from a conversation
      description: >
        Retrieve all messages from a conversation, ordered by timestamp (oldest first).
      operationId: getMessagesFromConversation
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/conversation_id'
      responses:
        '200':
          description: Messages loaded successfully
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Message'
        '400':
          description: Invalid request (e.g., invalid conversation ID)
        '401':
          description: Unauthorized (user not logged in)
        '403':
          description: Forbidden (user is not a member of the conversation)
        '404':
          description: Conversation not found
        '500':
          description: Internal server error
  /conversations/send-message/{conversation_id}:
    post:
      tags:
        - messages
      summary: Send a message
      description: > 
        Send a message on an existing conversation
      operationId: sendMessage
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/conversation_id'
      requestBody:
        description: Message details to send
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "Ciao come stai?"
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                    example: "1"
        '400':
          description: Invalid request
        '404':
          description: Conversation not found 
  /conversations/delete-message/{conversation_id}/message/{message_id}:
    delete:
      tags:
        - messages
      summary: Delete a sent message
      operationId: deleteMessage
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/conversation_id'
      - $ref: '#/components/parameters/message_id'
      responses:
        '204':
          description: Message deleted successfully
    post:
      tags:
        - messages
      summary: Forward a message to another conversation
      operationId: forwardMessage
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/conversation_id'
      - $ref: '#/components/parameters/message_id'
      requestBody:
        description: Message forwarding details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: string
                  example: "3"
      responses:
        '201':
          description: Message forwarded successfully
  /conversations/react/{conversation_id}/messages/{message_id}:
    post:
      tags:
        - messages
      summary: Add a comment to a message
      operationId: commentMessage
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/conversation_id'
      - $ref: '#/components/parameters/message_id'
      requestBody:
        description: Comment details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: Comment added successfully
  /conversations/delete-react/{conversation_id}/messages/{message_id}:
    delete:
      tags:
        - messages
      summary: Remove a comment from a message
      operationId: uncommentMessage
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/conversation_id'
      - $ref: '#/components/parameters/message_id'
      responses:
        '204':
          description: Comment removed successfully
  /conversations/create-group:
    post:
      tags:
        - groups
      summary: Create a new group
      description: Creates a new group with the specified members.
      operationId: createGroup
      security:
        - bearerAuth: []
      requestBody:
        description: Group details to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGroup'
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    example: "1"
        '400':
          description: Invalid request
  /conversations/group/change-name/{group_id}:
    patch:
      tags:
        - groups
      summary: Change the group's name
      operationId: setGroupName
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/group_id'
      requestBody:
        description: New group name
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "New Study Group"
      responses:
        '200':
          description: Group name updated successfully
        '404':
          description: Group not found
  /conversations/group/add/{group_id}:
    post:
      parameters:
      - $ref: '#/components/parameters/group_id'
      tags:
        - groups
      summary: Add a user to a group
      operationId: addToGroup
      security:
        - bearerAuth: []
      requestBody:
        description: User ID to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "hanni"
      responses:
        '200':
          description: User added to group
  /conversations/group/leave/{group_id}:
    delete:
      tags:
        - groups
      summary: Leave a group
      operationId: leaveGroup
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/group_id'
      responses:
        '200':
          description: User left the group successfully
        '404':
          description: Group not found
  /conversations/group/update-photo/{group_id}:
    patch:
      tags:
        - groups
      summary: Update group photo
      operationId: setGroupPhoto
      security:
        - bearerAuth: []
      parameters:
      - $ref: '#/components/parameters/group_id'
      requestBody:
        description: New group photo 
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Group photo updated successfully
        '404':
          description: Group not found
  /conversations/group/get-photo/{conversation_id}:
    get:
      tags:
        - groups
      summary: Get the photo of a conversation
      description: >
        Retrieves the photo of a conversation by its ID. The photo is returned as a binary image file.
      operationId: getConversationPhoto
      parameters:
        - $ref: '#/components/parameters/conversation_id'
      responses:
        '200':
          description: Photo retrieved successfully
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
        '404':
          description: Conversation or photo not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
  /user/modify-username:
    patch:
      tags: 
        - users
      summary: Update the logged in user's username
      operationId: setMyUserName
      security:
        - bearerAuth: []
      requestBody:
        description: New username to set
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_name: 
                  type: string
                  example: "godski"
      responses:
        '200':
          description: Username updated successfully
  /user/update-photo:
    patch:
      tags:
        - users
      summary: Update user profile photo
      operationId: setMyPhoto
      security:
        - bearerAuth: []
      requestBody:
        description: New profile photo
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Profile photo updated successfully
        '400':
          description: Invalid photo
  /user/get-photo/{user_id}:
    get:
      tags:
        - users
      summary: Get the photo of a user
      description: >
        Retrieves the photo of a user by their ID. If the user does not have a photo, a default photo is returned.
      operationId: getUserPhoto
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose photo is to be retrieved.
          schema:
            type: string
      responses:
        '200':
          description: Photo retrieved successfully
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
        '404':
          description: User not found or photo not set
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

                
    
components:
  parameters:
    message_id:
      schema:
        type: string
      name: message_id
      in: path
      required: true
      description: The ID of the message
      allowEmptyValue: false
    group_id:
      schema:
        type: string
      name: group_id
      in: path
      required: true
      description: The ID of the group
      allowEmptyValue: false
    conversation_id:
      schema:
        type: string
      name: conversation_id
      in: path
      required: true
      description: The conversation ID
      allowEmptyValue: false
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    NewGroup:
      type: object
      properties:
        name:
          type: string
          example: "Group Example"
        members:
          type: array
          items:
            type: string
            example: "hanni"
      required:
        - name
        - members
    Message:
      type: object
      properties:
        message_id:
          type: string
          example: "1"
        sender_id:
          type: string
          example: "1"
        content:
          type: string
          example: "Hello! today is the 1st of the month"
        timestamp:
          type: string
          format: date-time
          example: "2025-01-03T10:15:30Z"
        status:
          type: string
          enum:
          - sent
          - received
          - read
        reactions:
          type: array
          items:
            type: object
            properties:
              user_id:
                type: string
                example: "1"
              reaction:
                type: string
                example: "xD"
    Conversation:
      type: object
      properties:
        conversation_id:
          type: string
          example: "1"
        name:
          type: string
          example: "Giorgio"
        type:
          type: string
          enum:
            - private
            - group
          example: "private"
        creator_id:
          type: string
          example: "1"
        photo:
          type: string
          format: binary
          example: ""
          nullable: true
        last_message:
          type: string
          example: "reply to my message!"
          nullable: true
      required:
        - id
        - type
    Comment:
      type: object
      properties:
        emoji:
          type: string
          description: The emoji used as a reaction
          example: "👍"
      required:
        - emoji
